Creacion de Arrays

Arrays desde Listas: Puedes crear un array de NumPy a partir de una lista de Python usando la función np.array

In [1]:
import numpy as np

lista = [1, 2, 3, 4, 5]
array = np.array(lista)
print(array)

[1 2 3 4 5]


Arrays de Ceros y Unos: 
NumPy también proporciona funciones para crear arrays llenos de ceros o unos, lo cual es útil para inicializar arrays antes de llenarlos con datos.

In [2]:
array_ceros = np.zeros(5)
print(array_ceros)

array_unos = np.ones((3, 4))
print(array_unos)

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Arrays con Rangos: 
La función np.arange crea un array con valores en un rango específico, similar a la función range de Python.


In [3]:
array_rango = np.arange(10)
print(array_rango)

array_rango_paso = np.arange(0, 10, 2)
print(array_rango_paso)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


Arrays con Valores Aleatorios: 
NumPy proporciona funciones para crear arrays con valores aleatorios. Estas funciones son útiles para tareas como la inicialización aleatoria de parámetros en aprendizaje automático o para simulaciones.

In [4]:
array_aleatorio = np.random.random(5)
print(array_aleatorio)

array_aleatorio_entero = np.random.randint(0, 10, size=(3, 3))
print(array_aleatorio_entero)

[0.08319743 0.92677741 0.38161874 0.5639349  0.97821112]
[[4 1 6]
 [9 2 9]
 [0 6 1]]


Propiedades y Métodos de los Arrays

Una vez que tenemos arrays, es importante conocer sus propiedades y algunos métodos útiles para trabajar con ellos.

In [5]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)
print(array.size)
print(array.ndim)

(2, 3)
6
2


Propiedades Básicas:
Forma (shape): Devuelve una tupla con las dimensiones del array.
Tamaño (size): Devuelve el número total de elementos en el array.
Dimensión (ndim): Devuelve el número de dimensiones del array.
 

Métodos Útiles
reshape: Cambia la forma del array sin cambiar sus datos.
flatten: Convierte un array multidimensional en un array unidimensional.


In [6]:
array_reshape = array.reshape((3, 2))
print(array_reshape)
#[[1 2]
# [3 4]
# [5 6]]
array_flatten = array.flatten()
print(array_flatten)
#[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


Operaciones Básicas con Arrays
NumPy permite realizar operaciones matemáticas básicas de manera eficiente.

Suma y Resta: Puedes sumar o restar arrays de la misma forma elemento por elemento.

In [8]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

suma = array1 + array2
resta = array1 - array2

print("Suma:", suma)
print("Resta:", resta)

#Suma: [5 7 9]
#Resta: [-3 -3 -3]

Suma: [5 7 9]
Resta: [-3 -3 -3]


Multiplicación y División: La multiplicación y división también se realizan elemento por elemento.

In [10]:
multiplicacion = array1 * array2
division = array1 / array2

print("Multiplicación:", multiplicacion)
print("División:", division)

#Multiplicación: [ 4 10 18]
#División: [0.25 0.4  0.5 ]

print(array1)
print(array2)

Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]
[1 2 3]
[4 5 6]


Operaciones Universales (ufuncs): 
NumPy proporciona funciones universales (ufuncs) que realizan operaciones elemento por elemento.

In [11]:
array = np.array([1, 2, 3])

sqrt = np.sqrt(array)
log = np.log(array)

print("Raíz cuadrada:", sqrt)
print("Logaritmo natural:", log)

#Raíz cuadrada: [1.         1.41421356 1.73205081]
#Logaritmo natural: [0.         0.69314718 1.09861229]

Raíz cuadrada: [1.         1.41421356 1.73205081]
Logaritmo natural: [0.         0.69314718 1.09861229]


ndexación y Slicing de Arrays
La indexación y el slicing son técnicas para acceder a elementos específicos de un array.

Indexación Básica:Puedes acceder a elementos individuales utilizando índices.

In [12]:
array = np.array([1, 2, 3, 4, 5])
print(array[0])  # Primer elemento
print(array[-1])  # Último elemento

1
5


Slicing: Puedes acceder a subarrays utilizando la notación de slicing.

In [13]:
array = np.array([1, 2, 3, 4, 5])
print(array[1:4])  # Elementos del índice 1 al 3
print(array[:3])  # Primeros tres elementos
print(array[2:])  # Elementos desde el índice 2 hasta el final

#[2 3 4]
#[1 2 3]
#[3 4 5]

[2 3 4]
[1 2 3]
[3 4 5]


Indexación y Slicing en Arrays Multidimensionales: 
La indexación y el slicing funcionan de manera similar en arrays multidimensionales.

In [14]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array[1, 2])  # Elemento en la fila 1, columna 2
print(array[0:2, 1:3])  # Subarray desde fila 0 a 1 y columna 1 a 2

#6
#[[2 3]
#[5 6]]

6
[[2 3]
 [5 6]]


Agregaciones y Estadísticas
NumPy proporciona funciones para realizar operaciones de agregación y calcular estadísticas básicas.

Suma y Producto: Puedes calcular la suma y el producto de todos los elementos de un array.

In [15]:
array = np.array([1, 2, 3, 4, 5])
print(np.sum(array))  # Suma de todos los elementos
print(np.prod(array))  # Producto de todos los elementos

# 15
# 120

15
120


Estadísticas Básicas: NumPy también proporciona funciones para calcular estadísticas básicas.

In [16]:
print(np.mean(array))  # Media (promedio)
print(np.median(array))  # Mediana
print(np.std(array))  # Desviación estándar
print(np.var(array))  # Varianza

# 3.0
# 3.0
# 1.4142135623730951
# 2.0

3.0
3.0
1.4142135623730951
2.0


Agregaciones en Arrays Multidimensionales: 
Puedes realizar agregaciones a lo largo de un eje específico en arrays multidimensionales.

In [17]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sum(array, axis=0))  # Suma a lo largo de las columnas
print(np.sum(array, axis=1))  # Suma a lo largo de las filas

# [12 15 18]
# [ 6 15 24]

[12 15 18]
[ 6 15 24]
