Numpy

In [1]:
import numpy as np

# Crear una lista unidimensional
lista_1d = [1, 2, 3, 4, 5]

# Convertir la lista en un arreglo de NumPy
arreglo_1d = np.array(lista_1d)
print("Arreglo 1D:")
print(arreglo_1d)

# Crear una lista bidimensional
lista_2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Convertir la lista en un arreglo de NumPy
arreglo_2d = np.array(lista_2d)
print("\nArreglo 2D:")
print(arreglo_2d)

# Acceder a elementos
elemento_1d = arreglo_1d[1]  # Acceder al segundo elemento
print(f"\nElemento en el índice 1 del arreglo 1D: {elemento_1d}")

elemento_2d = arreglo_2d[0, 2]  # Acceder al elemento en la primera fila, tercera columna
print(f"Elemento en la fila 0, columna 2 del arreglo 2D: {elemento_2d}")

# Calcular la suma de todos los elementos del arreglo 1D
suma_total = np.sum(arreglo_1d)
print(f"\nSuma total de los elementos del arreglo 1D: {suma_total}")

# Calcular la suma de cada columna del arreglo 2D
suma_columnas = np.sum(arreglo_2d, axis=0)
print(f"\nSuma de cada columna del arreglo 2D: {suma_columnas}")

# Calcular la suma de cada fila del arreglo 2D
suma_filas = np.sum(arreglo_2d, axis=1)
print(f"\nSuma de cada fila del arreglo 2D: {suma_filas}")


Arreglo 1D:
[1 2 3 4 5]

Arreglo 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Elemento en el índice 1 del arreglo 1D: 2
Elemento en la fila 0, columna 2 del arreglo 2D: 3

Suma total de los elementos del arreglo 1D: 15

Suma de cada columna del arreglo 2D: [12 15 18]

Suma de cada fila del arreglo 2D: [ 6 15 24]


Geolocalizacion

In [2]:
import folium

# Crear un mapa centrado en una ubicación específica
mapa = folium.Map(location=[-25.2744, 133.7751], zoom_start=4)

# Agregar un marcador
folium.Marker(location=[-25.2744, 133.7751], popup='Australia').add_to(mapa)

# Mostrar el mapa
mapa.save('mapa.html')


ModuleNotFoundError: No module named 'folium'

In [ ]:
import folium

# Crear un mapa centrado en Asunción, Paraguay
asuncion_map = folium.Map(location=[-25.2637, -57.5759], zoom_start=12)

# Añadir un marcador en el centro de Asunción
folium.Marker(
    location=[-25.2637, -57.5759],
    popup='Asunción',
    icon=folium.Icon(color='blue')
).add_to(asuncion_map)

# Guardar el mapa en un archivo HTML
asuncion_map.save("mapa_asuncion.html")

# Mostrar el mapa (en un entorno Jupyter o compatible)
asuncion_map

In [ ]:
import folium

# Crear un mapa centrado en Asunción, Paraguay
asuncion_map = folium.Map(location=[-25.2637, -57.5759], zoom_start=12)

# Coordenadas de los tres puntos
punto1 = [-25.2637, -57.5759]  # Ejemplo: Centro de Asunción
punto2 = [-25.2949, -57.6483]  # Ejemplo: Costanera de Asunción
punto3 = [-25.2764, -57.5753]  # Ejemplo: Parque Ñu Guasu

# Añadir marcadores en los puntos
folium.Marker(
    location=punto1,
    popup='Centro de Asunción',
    icon=folium.Icon(color='blue')
).add_to(asuncion_map)

folium.Marker(
    location=punto2,
    popup='Costanera de Asunción',
    icon=folium.Icon(color='green')
).add_to(asuncion_map)

folium.Marker(
    location=punto3,
    popup='Parque Ñu Guasu',
    icon=folium.Icon(color='red')
).add_to(asuncion_map)

# Crear una ruta entre los puntos
ruta = folium.PolyLine(locations=[punto1, punto2, punto3], color='purple', weight=5, opacity=0.6)
asuncion_map.add_child(ruta)

# Guardar el mapa en un archivo HTML
asuncion_map.save("mapa_ruta_asuncion.html")

# Mostrar el mapa (en un entorno Jupyter o compatible)
asuncion_map


In [ ]:
import folium

# Crear un mapa centrado en Asunción, Paraguay
asuncion_map = folium.Map(location=[-25.2637, -57.5759], zoom_start=12)

# Coordenadas de los tres puntos
punto1 = [-25.2637, -57.5759]  # Ejemplo: Centro de Asunción
punto2 = [-25.2949, -57.6483]  # Ejemplo: Costanera de Asunción
punto3 = [-25.2764, -57.5753]  # Ejemplo: Parque Ñu Guasu

# Añadir marcadores con referencias
folium.Marker(
    location=punto1,
    popup=('<strong>Centro de Asunción</strong><br>'
            'Referencias:<br>'
            '<a href="https://es.wikipedia.org/wiki/Centro_de_Asunci%C3%B3n" target="_blank">Más información</a>'),
    icon=folium.Icon(color='blue')
).add_to(asuncion_map)

folium.Marker(
    location=punto2,
    popup=('<strong>Costanera de Asunción</strong><br>'
            'Referencias:<br>'
            '<a href="https://www.paraguay.com/nacionales/ya-se-inauguro-la-costanera-de-asuncion-186054" target="_blank">Más información</a>'),
    icon=folium.Icon(color='green')
).add_to(asuncion_map)

folium.Marker(
    location=punto3,
    popup=('<strong>Parque Ñu Guasu</strong><br>'
            'Referencias:<br>'
            '<a href="https://parques.abc.gov.py/parque-nu-guasu" target="_blank">Más información</a>'),
    icon=folium.Icon(color='red')
).add_to(asuncion_map)

# Crear una ruta entre los puntos
ruta = folium.PolyLine(locations=[punto1, punto2, punto3], color='purple', weight=5, opacity=0.6)
asuncion_map.add_child(ruta)

# Guardar el mapa en un archivo HTML
asuncion_map.save("mapa_ruta_asuncion_con_referencias.html")

# Mostrar el mapa (en un entorno Jupyter o compatible)
asuncion_map


In [13]:
import matplotlib.pyplot as plt
import mplleaflet

# Datos de ejemplo
latitudes = [-25.2637, -25.2949, -25.2764]
longitudes = [-57.5759, -57.6483, -57.5753]
nombres = ['Centro', 'Costanera', 'Parque Ñu Guasu']

# Crear una figura
plt.figure(figsize=(10, 10))

# Graficar los puntos
plt.scatter(longitudes, latitudes, color='blue')

# Añadir etiquetas
for nombre, lat, lon in zip(nombres, latitudes, longitudes):
    plt.annotate(nombre, xy=(lon, lat), xytext=(5, 5), textcoords='offset points')

# Convertir a mapa interactivo
mplleaflet.show()


AttributeError: 'XAxis' object has no attribute '_gridOnMajor'

In [15]:
import folium

# Crear un mapa centrado en Asunción, Paraguay
mapa = folium.Map(location=[-25.2637, -57.5759], zoom_start=12)

# Definir los puntos de interés
puntos = [
    {"nombre": "Centro de Asunción", "coordenadas": [-25.2637, -57.5759]},
    {"nombre": "Costanera de Asunción", "coordenadas": [-25.2949, -57.6483]},
    {"nombre": "Parque Ñu Guasu", "coordenadas": [-25.2764, -57.5753]},
]

# Añadir marcadores al mapa
for punto in puntos:
    folium.Marker(
        location=punto["coordenadas"],
        popup=punto["nombre"],
        icon=folium.Icon(color='blue')
    ).add_to(mapa)

# Conectar los puntos con una línea
folium.PolyLine(locations=[punto["coordenadas"] for punto in puntos], color='red').add_to(mapa)

# Mostrar el mapa
mapa.save("mapa_asuncion.html")  # Guarda el mapa en un archivo HTML
